###########
# site.url, site.title

url:   'http://rawcopy.org'
title: 'rawcopy'
# google_analytics: 'UA-23985298-11'

########
# more settings

#markdown: kramdown
markdown: redcarpet
pygments: true


sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

