###########
# site.url, site.title

url:   'http://rawcopy.github.io'
title: 'rawcopy'


########
# more settings

#markdown: kramdown
#markdown: redcarpet
#pygments: true
highlighter: pygments

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

